(()=>{'use strict';
const $=id=>document.getElementById(id),endpoint='/api/account-request-code?console=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page=1,current=[],total=0,busy=false,loadVersion=0;
const date=v=>{if(!v)return '—';const d=new Date(String(v).slice(0,10)+'T12:00:00Z');return Number.isNaN(+d)?'—':d.toLocaleDateString('es-AR',{timeZone:'UTC'})};
const money=v=>v==null||v===''||!Number.isFinite(Number(v))?'—':'USD '+Number(v).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});
const recordedMoney=(v,c)=>v==null||v===''||!Number.isFinite(Number(v))?'—':esc(c||'')+' '+Number(v).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});
const marginSummary=rows=>{const totals={};for(const r of rows){const f=r.finance||{};if(f.commissionAmount!=null&&f.commissionCurrency)totals[f.commissionCurrency]=(totals[f.commissionCurrency]||0)+Number(f.commissionAmount)}return Object.entries(totals).map(([c,v])=>c+' '+v.toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2})).join(' · ')||'—'};
function note(id,text,error=false){$(id).textContent=text;$(id).classList.toggle('error',error)}
async function api(params={},body){const qs=new URLSearchParams({console:'1',...params});const r=await fetch('/api/account-request-code?'+qs,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,purpose:'admin-console'})}:{})});let j;try{j=await r.json()}catch{throw Error('No pudimos conectar con la consola.')};if(!r.ok){const e=Error(j.error||'No pudimos completar la consulta.');e.status=r.status;throw e}return j}
function showLogin(){loadVersion++;$('dashboard').hidden=true;$('logout').hidden=true;$('login').hidden=false;$('initialMessage').hidden=true;current=[];$('rows').replaceChildren();$('detail').close();$('detailContent').replaceChildren()}
const badge=r=>'<span class="badge '+(['confirmada','cancelada'].includes(r.estado)?r.estado:'')+'">'+esc(r.estado||'Sin estado')+'</span><br><span class="badge '+(r.booking_environment==='sandbox'?'test':r.booking_environment==='production'?'real':'')+'">'+(r.booking_environment==='sandbox'?'Prueba':r.booking_environment==='production'?'Real':'Entorno sin registrar')+'</span>';
async function load(){const version=++loadVersion;busy=true;$('refresh').disabled=true;note('message','Cargando reservas…');try{
const j=await api({page:String(page),q:$('search').value,status:$('status').value,environment:$('environment').value,from:$('from').value,to:$('to').value});if(version!==loadVersion)return;
current=j.reservations||[];total=j.total;page=j.page;$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('initialMessage').hidden=true;$('operatorEmail').textContent=j.email;
$('total').textContent=total;$('confirmed').textContent=current.filter(x=>x.estado==='confirmada').length;$('testCount').textContent='Prueba: '+current.filter(x=>x.booking_environment==='sandbox').length+' · sin entorno: '+current.filter(x=>!['sandbox','production'].includes(x.booking_environment)).length;$('amount').textContent=money(current.reduce((sum,x)=>sum+(Number(x.total_usd)||0),0));$('margin').textContent=marginSummary(current);$('mailCount').textContent=current.filter(x=>x.email_sent===true||x.email_sent==='true').length+' / '+current.length;
$('rows').innerHTML=current.map((r,i)=>'<tr><td><span class="code">'+esc(r.booking_id||'—')+'</span><small>'+esc([r.nombre,r.apellido].filter(Boolean).join(' ')||'Sin nombre')+'</small><small>'+esc(r.email||'—')+'</small></td><td><strong>'+esc(r.hotel_nombre||'Alojamiento')+'</strong><small>'+esc(r.habitacion_nombre||'—')+'</small></td><td>'+date(r.checkin)+' → '+date(r.checkout)+'<small>'+esc(r.noches??'—')+' noches · '+esc(r.habitaciones??'—')+' hab.</small></td><td><strong>'+money(r.total_usd)+'</strong></td><td>'+recordedMoney(r.finance?.commissionAmount,r.finance?.commissionCurrency)+'</td><td>'+badge(r)+'</td><td>'+(r.email_sent===true||r.email_sent==='true'?'✓ Enviado':r.email_sent===false||r.email_sent==='false'?'Pendiente':'Sin registro')+'</td><td><button class="view" data-row="'+i+'" aria-label="Ver reserva '+esc(r.booking_id)+'">Ver detalle</button></td></tr>').join('');
$('empty').hidden=current.length>0;$('pageInfo').textContent='Página '+page+' de '+Math.max(1,Math.ceil(total/25))+' · '+total+' reservas';$('previous').disabled=page<=1;$('next').disabled=page*25>=total;$('export').disabled=!current.length;note('message','');
}catch(e){if(version!==loadVersion)return;if(e.status===401){showLogin();note('loginMessage','Ingresá para consultar las reservas.')}else{current=[];total=0;$('rows').replaceChildren();['total','confirmed','amount','margin','mailCount','testCount','pageInfo'].forEach(id=>$(id).textContent='—');$('empty').hidden=true;$('export').disabled=true;$('previous').disabled=true;$('next').disabled=true;note($('dashboard').hidden?'initialMessage':'message',e.message,true)}}finally{if(version===loadVersion){busy=false;$('refresh').disabled=false}}}
function pair(label,value){return '<div><dt>'+esc(label)+'</dt><dd>'+esc(value??'—')+'</dd></div>'}
function financePanel(r){
 const f=r.finance||{},d=f.invoiceDraft||{};
 const option=(value,label,selected)=>'<option value="'+value+'" '+(selected?'selected':'')+'>'+label+'</option>';
 return '<section class="detail-section"><h3>Registro económico interno</h3><p>Importes anotados manualmente para control interno; el margen no es una liquidación contable.</p><form id="financeForm" class="finance-form" data-booking-id="'+esc(r.booking_id)+'"><div class="financial-grid">'+
 '<div><label for="supplierBookingId">Código del proveedor</label><input id="supplierBookingId" name="supplierBookingId" maxlength="120" value="'+esc(f.supplierBookingId||r.confirmacion_hotel||'')+'"></div>'+
 '<div><label for="supplierCost">Costo del proveedor</label><input id="supplierCost" name="supplierCost" type="number" min="0" step="0.01" value="'+esc(f.supplierCost??'')+'"></div>'+
 '<div><label for="supplierCurrency">Moneda del costo</label><input id="supplierCurrency" name="supplierCurrency" maxlength="3" placeholder="USD" value="'+esc(f.supplierCurrency||'')+'"></div>'+
 '<div><label for="commissionAmount">Comisión/margen anotado</label><input id="commissionAmount" name="commissionAmount" type="number" min="0" step="0.01" value="'+esc(f.commissionAmount??'')+'"></div>'+
 '<div><label for="commissionCurrency">Moneda del margen</label><input id="commissionCurrency" name="commissionCurrency" maxlength="3" placeholder="USD" value="'+esc(f.commissionCurrency||'')+'"></div>'+
 '<div><label for="supplierPaymentStatus">Pago al proveedor</label><select id="supplierPaymentStatus" name="supplierPaymentStatus">'+option('unknown','Sin registrar',!f.supplierPaymentStatus||f.supplierPaymentStatus==='unknown')+option('pending','Pendiente',f.supplierPaymentStatus==='pending')+option('paid','Pagado',f.supplierPaymentStatus==='paid')+option('partial','Parcial',f.supplierPaymentStatus==='partial')+option('refunded','Reintegrado',f.supplierPaymentStatus==='refunded')+'</select></div>'+
 '<div><label for="supplierPaidAt">Fecha del pago</label><input id="supplierPaidAt" name="supplierPaidAt" type="date" value="'+esc(f.supplierPaidAt||'')+'"></div>'+
 '<div class="wide"><label for="financeNotes">Notas internas</label><input id="financeNotes" name="notes" maxlength="500" value="'+esc(f.notes||'')+'"></div></div><button class="primary" type="submit">Guardar registro</button></form></section>'+
 '<section class="detail-section"><h3>Borrador de factura</h3><p><strong>Borrador interno, sin validez fiscal. No se envía al cliente ni a ARCA.</strong></p><form id="draftForm" class="finance-form" data-booking-id="'+esc(r.booking_id)+'"><div class="financial-grid">'+
 '<div><label for="recipientType">Destinatario</label><select id="recipientType" name="recipientType">'+option('undecided','A definir',!d.recipientType||d.recipientType==='undecided')+option('customer','Cliente',d.recipientType==='customer')+option('supplier','Proveedor',d.recipientType==='supplier')+'</select></div>'+
 '<div><label for="documentType">Tipo de comprobante</label><select id="documentType" name="documentType">'+option('undecided','A definir',!d.documentType||d.documentType==='undecided')+['A','B','C','E'].map(x=>option(x,x,d.documentType===x)).join('')+'</select></div>'+
 '<div><label for="recipientName">Nombre o razón social</label><input id="recipientName" name="recipientName" maxlength="160" value="'+esc(d.recipientName||'')+'"></div>'+
 '<div><label for="recipientTaxId">CUIT / identificación fiscal</label><input id="recipientTaxId" name="recipientTaxId" maxlength="30" value="'+esc(d.recipientTaxId||'')+'"></div>'+
 '<div><label for="invoiceAmount">Importe del borrador</label><input id="invoiceAmount" name="invoiceAmount" type="number" min="0" step="0.01" value="'+esc(d.amount??'')+'"></div>'+
 '<div><label for="invoiceCurrency">Moneda</label><input id="invoiceCurrency" name="invoiceCurrency" maxlength="3" placeholder="ARS / USD" value="'+esc(d.currency||'')+'"></div>'+
 '<div class="wide"><label for="invoiceConcept">Concepto interno</label><input id="invoiceConcept" name="concept" maxlength="240" value="'+esc(d.concept||'')+'"></div>'+
 '</div><button type="submit">Guardar borrador</button></form>'+(d.updatedAt?'<p class="muted">Borrador guardado el '+esc(date(d.updatedAt))+'</p>':'')+'</section>';
}
function saveFormSnapshot(form){return JSON.stringify([...new FormData(form).entries()])}
function saveFormHasData(form){return [...new FormData(form).entries()].some(([name,value])=>{const v=String(value??'').trim();return v&&!((name==='supplierPaymentStatus'&&v==='unknown')||(['recipientType','documentType'].includes(name)&&v==='undecided'))})}
function updateSaveButton(form){const button=form.querySelector('button[type="submit"]');if(!button)return;const dirty=saveFormSnapshot(form)!==(form.dataset.savedSnapshot||''),hasData=saveFormHasData(form),busy=form.dataset.saving==='true',saved=form.dataset.savedOnce==='true';button.disabled=busy||!dirty||(!hasData&&!saved);button.textContent=busy?'Guardando…':dirty?(hasData||saved?(saved?'Guardar cambios':form.id==='financeForm'?'Guardar registro':'Guardar borrador'):'Ingresá un dato'):saved?(form.id==='financeForm'?'Guardado':'Borrador guardado'):'Sin cambios'}
function initSaveForms(){for(const form of $('detailContent').querySelectorAll('#financeForm,#draftForm')){form.dataset.savedSnapshot=saveFormSnapshot(form);form.dataset.savedOnce=form.id==='financeForm'?(form.querySelector('[name="supplierCost"]').value!==''||form.querySelector('[name="commissionAmount"]').value!==''||form.querySelector('[name="notes"]').value!==''?'true':'false'):(form.querySelector('[name="invoiceAmount"]').value!==''||form.querySelector('[name="concept"]').value!==''?'true':'false');updateSaveButton(form)}}
async function detail(index){const row=current[index];if(!row)return;const id=row.booking_id;$('detailContent').replaceChildren();note('detailMessage','Cargando detalle…');$('detail').showModal();try{const j=await api({bookingId:id});if(!$('detail').open)return;const r=j.reservations?.[0];if(!r)throw Error('No encontramos esta reserva.');const c=j.checkout;const emailSent=r.email_sent===true||r.email_sent==='true';
$('detailContent').innerHTML='<h2 style="margin-top:16px">'+esc(r.hotel_nombre||'Alojamiento')+'</h2><p class="code">'+esc(r.booking_id)+'</p>'+badge(r)+(r.booking_environment==='sandbox'?'<p class="test-note">Reserva de prueba: sin cobro ni alojamiento real.</p>':'')+'<dl class="detail-grid">'+pair('Huésped',[r.nombre,r.apellido].filter(Boolean).join(' '))+pair('Email',r.email)+pair('Teléfono',r.telefono)+pair('Confirmación del hotel',r.confirmacion_hotel)+pair('Entrada',date(r.checkin))+pair('Salida',date(r.checkout))+pair('Ocupación',(r.adultos??0)+' adultos · '+(r.ninos??0)+' niños · '+(r.habitaciones??0)+' habitaciones')+pair('Importe registrado',money(r.total_usd))+pair('Habitación',r.habitacion_nombre)+pair('Régimen',r.regimen)+pair('Creada',date(r.creado_en))+pair('Correo',emailSent?'Envío aceptado':r.email_sent===false||r.email_sent==='false'?'Pendiente':'Sin registro')+'</dl><section class="detail-section"><h3>Registro del pago</h3><p>'+esc(r.booking_environment==='sandbox'?'Esta operación es una simulación.':r.pagado===true?'La base de datos indica pago acreditado.':'Sin acreditación de cobro registrada. La confirmación de la reserva no prueba por sí sola el pago.')+'</p><p>Método: '+esc(r.payment_method||'Sin registrar')+'</p>'+(c?'<p>Circuito de reserva: '+esc(({prepared:'Pago preparado',ready:'Datos preparados para el pago',booking:'Confirmación en curso',confirmed:'Reserva confirmada',rejected:'Reserva rechazada',uncertain:'Confirmación por verificar'})[c.state]||c.state)+'. Registro en Mi cuenta: '+(c.saved?'guardado':'pendiente')+'.</p>':'<p>No hay un circuito de pago SDK vinculado a esta reserva.</p>')+'</section>'+financePanel(r)+'<section class="detail-section"><h3>Condiciones de cancelación</h3><p>'+esc(r.reembolsable===true?'Tarifa registrada como reembolsable.':r.reembolsable===false?'Tarifa registrada como no reembolsable.':'Condición no registrada.')+'</p><p>'+esc(policyText(r.politicas_cancelacion))+'</p></section>';initSaveForms();note('detailMessage','');
}catch(e){if(e.status===401){showLogin();note('loginMessage','La sesión venció. Volvé a ingresar.',true)}else note('detailMessage',e.message,true)}}
function policyText(p){const rows=Array.isArray(p)?p:p?.cancelPolicyInfos||p?.cancellationPolicies||[];if(!rows.length)return 'Consultá las condiciones del proveedor antes de gestionar una cancelación.';return rows.map(x=>[x.cancelTime?date(x.cancelTime):'',x.amount!=null?'Cargo: '+String(x.currency||'USD')+' '+x.amount:'',x.type||''].filter(Boolean).join(' · ')).join(' | ')}
$('emailForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;note('loginMessage','Enviando código…');try{const j=await api({},{action:'request',email:$('email').value});$('emailForm').hidden=true;$('codeForm').hidden=false;note('loginMessage',j.message);$('code').focus()}catch(e){note('loginMessage',e.message,true)}finally{button.disabled=false}});
$('codeForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;note('loginMessage','Validando acceso…');try{await api({},{action:'verify',email:$('email').value,code:$('code').value});$('code').value='';await load()}catch(e){note('loginMessage',e.message,true)}finally{button.disabled=false}});
$('changeEmail').onclick=()=>{$('codeForm').hidden=true;$('emailForm').hidden=false;$('code').value='';note('loginMessage','')};
$('logout').onclick=async()=>{try{await api({},{action:'logout'});showLogin();$('codeForm').hidden=true;$('emailForm').hidden=false;note('loginMessage','Sesión cerrada.')}catch(e){note('message',e.message,true)}};
$('filters').onsubmit=e=>{e.preventDefault();if($('from').value&&$('to').value&&$('from').value>$('to').value)return note('message','La fecha inicial debe ser anterior a la final.',true);page=1;load()};$('filters').onreset=()=>{setTimeout(()=>{page=1;load()},0)};$('refresh').onclick=()=>load();$('previous').onclick=()=>{if(!busy&&page>1){page--;load()}};$('next').onclick=()=>{if(!busy&&page*25<total){page++;load()}};$('rows').onclick=e=>{const b=e.target.closest('button[data-row]');if(b)detail(Number(b.dataset.row))};$('detailContent').addEventListener('input',e=>{const form=e.target.closest('#financeForm,#draftForm');if(form)updateSaveButton(form)});
$('detailContent').addEventListener('change',e=>{const form=e.target.closest('#financeForm,#draftForm');if(form)updateSaveButton(form)});
$('detailContent').addEventListener('submit',async e=>{const form=e.target;if(!['financeForm','draftForm'].includes(form.id))return;e.preventDefault();const button=form.querySelector('button[type="submit"]');if(form.dataset.saving==='true')return;if(saveFormSnapshot(form)===(form.dataset.savedSnapshot||'')){updateSaveButton(form);note('detailMessage','No hay cambios nuevos para guardar.');return}if(!saveFormHasData(form)&&form.dataset.savedOnce!=='true'){updateSaveButton(form);note('detailMessage','Ingresá al menos un dato antes de guardar.',true);return}const fields=Object.fromEntries(new FormData(form).entries()),snapshot=saveFormSnapshot(form),action=form.id==='financeForm'?'save-financials':'prepare-invoice';form.dataset.saving='true';updateSaveButton(form);note('detailMessage',form.id==='financeForm'?'Guardando registro…':'Guardando borrador…');try{const j=await api({}, {action,bookingId:form.dataset.bookingId,...fields});const row=current.find(x=>x.booking_id===form.dataset.bookingId);if(row)row.finance=j.finance;form.dataset.savedSnapshot=snapshot;form.dataset.savedOnce='true';await load();note('detailMessage',form.id==='financeForm'?'Registro interno guardado.':'Borrador interno guardado; no se emitió ni se compartió una factura.')}catch(err){note('detailMessage',err.message,true)}finally{form.dataset.saving='false';updateSaveButton(form)}});
$('closeDetail').onclick=()=>$('detail').close();
$('export').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+@-]/,'\t$&').replace(/"/g,'""')+'"';const columns=['Código','Huésped','Email','Hotel','Entrada','Salida','Total USD','Margen anotado','Moneda margen','Costo proveedor','Moneda costo','Pago proveedor','Estado','Entorno','Correo'];const csv='\uFEFF'+[columns,...current.map(r=>[r.booking_id,[r.nombre,r.apellido].filter(Boolean).join(' '),r.email,r.hotel_nombre,r.checkin,r.checkout,r.total_usd,r.finance?.commissionAmount??'',r.finance?.commissionCurrency||'',r.finance?.supplierCost??'',r.finance?.supplierCurrency||'',r.finance?.supplierPaymentStatus||'Sin registrar',r.estado,r.booking_environment||'Sin registrar',r.email_sent===true||r.email_sent==='true'?'Enviado':'Sin envío confirmado'])].map(row=>row.map(cell).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='valijeando-reservas-pagina-'+page+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
load();
})();
