import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import handler from '../api/account-request-code.js';
import {adminSessionToken,adminSession,adminCodeHash} from '../lib/admin-console.js';
const response=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers});
const email='hola@valijeando.com.ar';
const originHeaders={host:'www.valijeando.com.ar',origin:'https://www.valijeando.com.ar'};
async function run(mock,fn){const oldFetch=globalThis.fetch,oldEnv={...process.env};Object.assign(process.env,{SUPABASE_URL:'https://db.test',SUPABASE_SECRET_KEY:'unit-test-secret',RESEND_API_KEY:'unit-test-mail'});delete process.env.VALIJEANDO_ADMIN_EMAILS;delete process.env.ADMIN_CONSOLE_SECRET;delete process.env.MI_CUENTA_SECRET;globalThis.fetch=mock;try{await fn()}finally{globalThis.fetch=oldFetch;for(const k of Object.keys(process.env))if(!(k in oldEnv))delete process.env[k];Object.assign(process.env,oldEnv)}}
async function request({method='GET',query={console:'1'},body={},headers={}}={}){const res={statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(d){this.data=d;return this}};await handler({method,query,body,headers},res);return res}
const signed=()=>({'cookie':'__Host-valijeandoAdmin='+adminSessionToken(email)});
test('the admin API rejects unauthenticated requests before querying any table',async()=>run(()=>{throw Error('must not query')},async()=>{const r=await request();assert.equal(r.statusCode,401);assert.equal(r.headers['Cache-Control'],'private, no-store')}));
test('a customer token cannot authorize the console even for the owner email',async()=>run(()=>{throw Error('must not query')},async()=>{const b=Buffer.from(JSON.stringify({email,exp:Date.now()+60000})).toString('base64url'),s=crypto.createHmac('sha256','unit-test-secret').update(b).digest('base64url');const r=await request({headers:{cookie:'__Host-valijeandoAdmin='+b+'.'+s,authorization:'Bearer '+b+'.'+s}});assert.equal(r.statusCode,401)}));
test('expired, altered and removed-operator sessions fail closed',async()=>run(()=>{},async()=>{const t=adminSessionToken(email);assert.equal(adminSession({headers:{cookie:'__Host-valijeandoAdmin='+t}}).email,email);assert.equal(adminSession({headers:{cookie:'__Host-valijeandoAdmin='+t+'x'}}),null);const expired=adminSessionToken(email,Date.now()-3*60*60*1000);assert.equal(adminSession({headers:{cookie:'__Host-valijeandoAdmin='+expired}}),null);process.env.VALIJEANDO_ADMIN_EMAILS='another@example.test';assert.equal(adminSession({headers:{cookie:'__Host-valijeandoAdmin='+t}}),null)}));
test('cross-origin requests and unauthorized operators never send a code',async()=>run(()=>{throw Error('must not query')},async()=>{let r=await request({method:'POST',headers:{...originHeaders,origin:'https://other.test'},body:{action:'request',email}});assert.equal(r.statusCode,403);r=await request({method:'POST',headers:originHeaders,body:{action:'request',email:'customer@example.test'}});assert.equal(r.statusCode,403)}));
test('the console issues a distinct high-entropy, one-time code and never returns it',async()=>{let stored,mail;await run(async(url,opt)=>{if(String(url).includes('api.resend.com')){mail=JSON.parse(opt.body);return response({id:'mail'})}if(opt.method==='POST'){stored=JSON.parse(opt.body);return response({})}return response([])},async()=>{const r=await request({method:'POST',headers:originHeaders,body:{action:'request',email}});assert.equal(r.statusCode,200);const code=mail.html.match(/letter-spacing:3px">(\d{12})/)[1];assert.equal(stored.codigo_hash,adminCodeHash(email,code));assert.notEqual(stored.codigo_hash,crypto.createHmac('sha256','unit-test-secret').update(email+'|'+code).digest('hex'));assert.equal(JSON.stringify(r.data).includes(code),false);assert.deepEqual(mail.to,[email])})});
test('request throttling uses the persisted code timestamp',async()=>run(async()=>response([{vence_en:new Date(Date.now()+600000).toISOString()}]),async()=>{const r=await request({method:'POST',headers:originHeaders,body:{action:'request',email}});assert.equal(r.statusCode,429)}));
test('code verification consumes atomically and grants only an HttpOnly admin cookie',async()=>{let claimed=false;await run(async(url,opt)=>{assert.ok(url.includes('vence_en=gt.'));if(opt.method==='PATCH'){claimed=true;assert.ok(url.includes('usado=eq.false'));assert.equal(opt.headers.Prefer,'return=representation')}return response([{id:'row'}])},async()=>{const r=await request({method:'POST',headers:originHeaders,body:{action:'verify',email,code:'123456789012'}});assert.equal(r.statusCode,200);assert.equal(claimed,true);assert.equal(r.data.token,undefined);assert.match(r.headers['Set-Cookie'],/^__Host-valijeandoAdmin=/);assert.match(r.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Strict; Path=\//)})});
test('a concurrent claim failure never grants a console session',async()=>run(async(url,opt)=>response(opt.method==='PATCH'?[]:[{id:'row'}]),async()=>{const r=await request({method:'POST',headers:originHeaders,body:{action:'verify',email,code:'123456789012'}});assert.equal(r.statusCode,401);assert.equal(r.headers['Set-Cookie'],undefined)}));
test('queries are bounded, filters are applied server-side and sensitive provider data is omitted',async()=>run(async(url,opt)=>{const q=new URL(url).searchParams;assert.equal(q.get('limit'),'25');assert.equal(q.get('offset'),'25');assert.equal(q.get('estado'),'eq.confirmada');assert.equal(q.get('datos_proveedor->>valijeandoEnvironment'),'eq.sandbox');assert.match(q.get('or'),/hotel_nombre.ilike/);assert.equal(q.get('select').includes('transaction_id'),false);assert.equal(q.get('select').includes('provider_result'),false);assert.equal(opt.headers.Prefer,'count=exact');return response([{booking_id:'one',email_sent:true}],200,{'Content-Range':'25-25/26'})},async()=>{const r=await request({headers:signed(),query:{console:'1',page:'2',q:'hotel),email.eq.secret',status:'confirmada',environment:'sandbox'}});assert.equal(r.statusCode,200);assert.equal(r.data.total,26);assert.equal(r.data.page,2)}));
test('detail uses a canonical reservation id and returns only checkout status fields',async()=>{let calls=0;await run(async(url)=>{calls++;const q=new URL(url).searchParams;if(calls===1){assert.equal(q.get('booking_id'),'eq.booking-test');return response([{booking_id:'booking-test'}])}assert.equal(q.get('select'),'state,environment,email_sent,saved,created_at,updated_at,expires_at');return response([{state:'confirmed',saved:true}])},async()=>{const r=await request({headers:signed(),query:{console:'1',bookingId:'booking-test'}});assert.equal(r.data.checkout.state,'confirmed');assert.equal(calls,2)})});
test('logout expires the admin cookie without changing reservations',async()=>run(()=>{throw Error('must not query')},async()=>{const r=await request({method:'POST',headers:originHeaders,body:{action:'logout'}});assert.equal(r.statusCode,200);assert.match(r.headers['Set-Cookie'],/Max-Age=0/)}));
